// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.2
// LVGL version: 8.3.11
// Project name: pantalla_dht

#include "ui.h"

lv_obj_t * ui_Screen1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_lbltempval = NULL;
lv_obj_t * ui_lblhumval = NULL;
// event funtions

// build funtions

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -104);
    lv_obj_set_y(ui_Label1, -34);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "TEMP:");

    ui_Label2 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, 60);
    lv_obj_set_y(ui_Label2, -33);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "HUME:");

    ui_lbltempval = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lbltempval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lbltempval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lbltempval, -106);
    lv_obj_set_y(ui_lbltempval, 28);
    lv_obj_set_align(ui_lbltempval, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lbltempval, "11");

    ui_lblhumval = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_lblhumval, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_lblhumval, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_lblhumval, 59);
    lv_obj_set_y(ui_lblhumval, 24);
    lv_obj_set_align(ui_lblhumval, LV_ALIGN_CENTER);
    lv_label_set_text(ui_lblhumval, "22");

}

void ui_Screen1_screen_destroy(void)
{
    if(ui_Screen1) lv_obj_del(ui_Screen1);

    // NULL screen variables
    ui_Screen1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_lbltempval = NULL;
    ui_lblhumval = NULL;

}
